[[library]]
name = "libload_time_mpi_constants"
file = "/opt/mpitrampoline/lib/libload_time_mpi_constants.so"

[[library]]
name = "libmpi"
file = "/opt/mpitrampoline/lib/libmpitrampoline.so"

[[binary]]
name = "generate_compile_time_mpi_constants"
file = "/opt/mpitrampoline/bin/generate_compile_time_mpi_constants"

[[binary]]
name = "mpicc"
file = "/opt/mpitrampoline/bin/mpicc"

[[binary]]
name = "mpich_mpiexec"
file = "/opt/mpich/bin/mpiexec"

[[binary]]
name = "mpicxx"
file = "/opt/mpitrampoline/bin/mpicxx"

[[binary]]
name = "mpiexec"
file = "/opt/mpitrampoline/bin/mpiexec"

[[binary]]
name = "mpifc"
file = "/opt/mpitrampoline/bin/mpifc"

[[binary]]
name = "mpifort"
file = "/opt/mpitrampoline/bin/mpifort"

[[binary]]
name = "mpiwrapperexec"
file = "/opt/mpitrampoline/bin/mpiwrapperexec"
