maintainers:
- github: lilydjwg
update_on:
- source: github
  github: vim/vim
  lilac_throttle: 3d
- alias: python
- alias: ruby
# doesn't build with perl 5.38
# - alias: perl
- source: manual
  manual: 5.36
- source: manual
  manual: 6
