maintainers:
- github: lilydjwg

update_on:
- source: regex
  url: https://www.collectd.org/download.html
  regex: "collectd-(\\S+?).tar.bz2"
- alias: perl
- alias: python
- alias: libssl

repo_depends:
- liboping
