maintainers:
- github: lilydjwg

update_on:
- source: github
  github: collectd/collectd
  prefix: collectd-
  use_latest_release: true
- alias: perl
- alias: python
- alias: libssl

repo_depends:
- liboping
