maintainers:
- github: lilydjwg

update_on:
- source: regex
  url: https://collectd.org/download.html
  regex: "collectd-(\\S+?).tar.bz2"
- alias: perl
- source: manual
  manual: 1
- alias: python

repo_depends:
- liboping
