[[library]]
name = "libqt5concurrent"
file = "libQt5Concurrent"

[[library]]
name = "libqt5core"
file = "libQt5Core"

[[library]]
name = "libqt5dbus"
file = "libQt5DBus"

[[library]]
name = "libqt5gui"
file = "libQt5Gui"

[[library]]
name = "libqt5network"
file = "libQt5Network"

[[library]]
name = "libqt5opengl"
file = "libQt5OpenGL"

[[library]]
name = "libqt5printsupport"
file = "libQt5PrintSupport"

[[library]]
name = "libqt5sql"
file = "libQt5Sql"

[[library]]
name = "libqt5test"
file = "libQt5Test"

[[library]]
name = "libqt5widgets"
file = "libQt5Widgets"

[[library]]
name = "libqt5xml"
file = "libQt5Xml"
