[[library]]
name = "libgs"

[[binary]]
name = "gs"

[[binary]]
name = "gsc"
file = "gs"

[[binary]]
name = "gsx"

[[file]]
name = "dvipdf"

[[file]]
name = "eps2eps"

[[file]]
name = "gsbj"

[[file]]
name = "gsdj"

[[file]]
name = "gsdj500"

[[file]]
name = "gserrors_h"
file = "/usr/include/ghostscript/gserrors.h"

[[file]]
name = "gslj"

[[file]]
name = "gslp"

[[file]]
name = "gsnd"

[[file]]
name = "iapi_h"
file = "/usr/include/ghostscript/iapi.h"

[[file]]
name = "ierrors_h"
file = "/usr/include/ghostscript/ierrors.h"

[[file]]
name = "pdf2dsc"

[[file]]
name = "pdf2ps"

[[file]]
name = "pf2afm"

[[file]]
name = "pfbtopfa"

[[file]]
name = "pphs"

[[file]]
name = "printafm"

[[file]]
name = "ps2ascii"

[[file]]
name = "ps2epsi"

[[file]]
name = "ps2pdf"

[[file]]
name = "ps2pdf12"

[[file]]
name = "ps2pdf13"

[[file]]
name = "ps2pdf14"

[[file]]
name = "ps2pdfwr"

[[file]]
name = "ps2ps"

[[file]]
name = "ps2ps2"
