[[library]]
name = "libcmumps"
file = "libcmumps_seq.so"

[[library]]
name = "libdmumps"
file = "libdmumps_seq.so"

[[library]]
name = "libsmumps"
file = "libsmumps_seq.so"

[[library]]
name = "libzmumps"
file = "libzmumps_seq.so"
