[[library]]
name = "libhdf5"

[[library]]
name = "libhdf5_cpp"

[[library]]
name = "libhdf5_fortran"

[[library]]
name = "libhdf5_hl"

[[library]]
name = "libhdf5_hl_cpp"

[[library]]
name = "libhdf5_hl_fortran"

[[binary]]
name = "h5clear"

[[binary]]
name = "h5copy"

[[binary]]
name = "h5debug"

[[binary]]
name = "h5delete"

[[binary]]
name = "h5diff"

[[binary]]
name = "h5dump"

[[binary]]
name = "h5format_convert"

[[binary]]
name = "h5import"

[[binary]]
name = "h5jam"

[[binary]]
name = "h5ls"

[[binary]]
name = "h5mkgrp"

[[binary]]
name = "h5perf_serial"

[[binary]]
name = "h5repack"

[[binary]]
name = "h5repart"

[[binary]]
name = "h5stat"

[[binary]]
name = "h5unjam"

[[binary]]
name = "h5watch"
