[[library]]
name = "libIex"
file = "libIex-3_1.so"

[[library]]
name = "libIlmThread"
file = "libIlmThread-3_1.so"

[[library]]
name = "libOpenEXR"
file = "libOpenEXR-3_1.so"

[[library]]
name = "libOpenEXRCore"
file = "libOpenEXRCore-3_1.so"

[[library]]
name = "libOpenEXRUtil"
file = "libOpenEXRUtil-3_1.so"
