[[library]]
name = "libbvp_m_proxy"
file = "/usr/lib/julia/odeinterface/bvp_m_proxy"

[[library]]
name = "libbvpsol"
file = "/usr/lib/julia/odeinterface/bvpsol"

[[library]]
name = "libbvpsol_i32"
file = "/usr/lib/julia/odeinterface/bvpsol_i32"

[[library]]
name = "libcolnew"
file = "/usr/lib/julia/odeinterface/colnew"

[[library]]
name = "libcolnew_i32"
file = "/usr/lib/julia/odeinterface/colnew_i32"

[[library]]
name = "libddeabm"
file = "/usr/lib/julia/odeinterface/ddeabm"

[[library]]
name = "libddeabm_i32"
file = "/usr/lib/julia/odeinterface/ddeabm_i32"

[[library]]
name = "libddebdf"
file = "/usr/lib/julia/odeinterface/ddebdf"

[[library]]
name = "libddebdf_i32"
file = "/usr/lib/julia/odeinterface/ddebdf_i32"

[[library]]
name = "libdop853"
file = "/usr/lib/julia/odeinterface/dop853"

[[library]]
name = "libdop853_i32"
file = "/usr/lib/julia/odeinterface/dop853_i32"

[[library]]
name = "libdopri5"
file = "/usr/lib/julia/odeinterface/dopri5"

[[library]]
name = "libdopri5_i32"
file = "/usr/lib/julia/odeinterface/dopri5_i32"

[[library]]
name = "libodex"
file = "/usr/lib/julia/odeinterface/odex"

[[library]]
name = "libodex_i32"
file = "/usr/lib/julia/odeinterface/odex_i32"

[[library]]
name = "libradau"
file = "/usr/lib/julia/odeinterface/radau"

[[library]]
name = "libradau5"
file = "/usr/lib/julia/odeinterface/radau5"

[[library]]
name = "libradau5_i32"
file = "/usr/lib/julia/odeinterface/radau5_i32"

[[library]]
name = "libradau_i32"
file = "/usr/lib/julia/odeinterface/radau_i32"

[[library]]
name = "librodas"
file = "/usr/lib/julia/odeinterface/rodas"

[[library]]
name = "librodas_i32"
file = "/usr/lib/julia/odeinterface/rodas_i32"

[[library]]
name = "libseulex"
file = "/usr/lib/julia/odeinterface/seulex"

[[library]]
name = "libseulex_i32"
file = "/usr/lib/julia/odeinterface/seulex_i32"
