[[library]]
name = "libgdkpixbuf"
file = "libgdk_pixbuf-2.0"

[[binary]]
name = "gdk_pixbuf_query_loaders"
file = "gdk-pixbuf-query-loaders"

[[file]]
name = "gdk_pixbuf_loaders_dir"
file = "/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders"
literal = true
