[[library]]
name = "libEGL"

[[library]]
name = "libGL"

[[library]]
name = "libGLESv1_CM"
file = "libGLESv2" # Arch doesn't have this anymore

[[library]]
name = "libGLESv2"

[[library]]
name = "libGLX"

[[library]]
name = "libGLdispatch"

[[library]]
name = "libOpenGL"
