[[library]]
name = "libmpi"
file = "/opt/mpich/lib/libmpi.so"

[[library]]
name = "libmpicxx"
file = "/opt/mpich/lib/libmpicxx.so"

[[library]]
name = "libmpifort"
file = "/opt/mpich/lib/libmpifort.so"

[[binary]]
name = "mpiexec"
file = "/opt/mpich/bin/mpiexec"
