[[library]]
name = "libxcb"

[[library]]
name = "libxcb_composite"
file = "libxcb-composite.so"

[[library]]
name = "libxcb_damage"
file = "libxcb-damage.so"

[[library]]
name = "libxcb_dpms"
file = "libxcb-dpms.so"

[[library]]
name = "libxcb_dri2"
file = "libxcb-dri2.so"

[[library]]
name = "libxcb_dri3"
file = "libxcb-dri3.so"

[[library]]
name = "libxcb_glx"
file = "libxcb-glx.so"

[[library]]
name = "libxcb_present"
file = "libxcb-present.so"

[[library]]
name = "libxcb_randr"
file = "libxcb-randr.so"

[[library]]
name = "libxcb_record"
file = "libxcb-record.so"

[[library]]
name = "libxcb_render"
file = "libxcb-render.so"

[[library]]
name = "libxcb_res"
file = "libxcb-res.so"

[[library]]
name = "libxcb_screensaver"
file = "libxcb-screensaver.so"

[[library]]
name = "libxcb_shape"
file = "libxcb-shape.so"

[[library]]
name = "libxcb_shm"
file = "libxcb-shm.so"

[[library]]
name = "libxcb_sync"
file = "libxcb-sync.so"

[[library]]
name = "libxcb_xf86dri"
file = "libxcb-xf86dri.so"

[[library]]
name = "libxcb_xfixes"
file = "libxcb-xfixes.so"

[[library]]
name = "libxcb_xinerama"
file = "libxcb-xinerama.so"

[[library]]
name = "libxcb_xinput"
file = "libxcb-xinput.so"

[[library]]
name = "libxcb_xkb"
file = "libxcb-xkb.so"

[[library]]
name = "libxcb_xtest"
file = "libxcb-xtest.so"

[[library]]
name = "libxcb_xv"
file = "libxcb-xv.so"

[[library]]
name = "libxcb_xvmc"
file = "libxcb-xvmc.so"
