[[library]]
name = "libwayland_client"
file = "libwayland-client.so"

[[library]]
name = "libwayland_cursor"
file = "libwayland-cursor.so"

[[library]]
name = "libwayland_egl"
file = "libwayland-egl.so"

[[library]]
name = "libwayland_server"
file = "libwayland-server.so"

[[binary]]
name = "wayland_scanner"
file = "wayland-scanner"
